### ISSUE TITLE
First Download Sync Issues

### ISSUE THREAD

**Issue by branchfractal** [haven-protocol-org/haven-web-app#26]
After installing latest version and sending successful transactions, the wallet shows synced but transactions don't show up until app is uninstalled, the Haven directory is removed completely, and the app is reinstalled with vault restored from seed.

**Comment by MartyHav** [comment]
This is a weird issue. The case I observed:
Created a new wallet, didn't see the incoming transfer.
Restored the wallet from seed ( without deleting the old one, they can coexist ) and saw the incoming tx.

When trigger rescan_blockchain for the working wallet, its doing its job and does a full resync.
When trigger rescan_blockchain for the non-work wallet it's just skipping all the blocks. In the output we can see
`Skipped block by height` . The wallet-rpc seems to think, that it is already synced to that height.
The related line in the monero source code:
https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L3192

**Comment by luncht1me** [comment]
Can confirm something is weird with the wallet here when starting fresh.

Fresh download of vault off homepage, make a new wallet, send some transactions.... tx confirmed on chain, never shows in wallet, despite deleting wallet files, changing remote nodes, etc.

Re-import with seed phrase, resync, transactions are now present on newly imported wallet -- which is the same one that was created in the first place but doesn't ever sync.
