### ISSUE TITLE
Portfolio section takes half the screen on phone

### ISSUE THREAD

**Issue by g45t345rt** [haven-protocol-org/haven-web-app#39]
I feel that the portfolio block should be smaller depending on screen width.

I love using relative lengths units for padding and even font size. So you have bigger font size on 4k monitors and smaller font size on mobile phones.
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#ems_and_rems

![image](https://user-images.githubusercontent.com/49697006/118426688-ad610400-b699-11eb-9e6c-d9c2120cfdb7.png)

**Comment by pierrelafitte** [comment]
"Half" is subjectively relative to the height of a ones own phone not all phones. Regardless, this has been changed from 260px height to 200px height.

**Comment by pierrelafitte** [comment]
Marked as complete. Will be included in next public release.

https://github.com/haven-protocol-org/haven-web-app/commit/40bc252b7386b5acd4a7e559346dfcc19c23fd2a
