### ISSUE TITLE
What about icons on action link

### ISSUE THREAD

**Issue by g45t345rt** [haven-protocol-org/haven-web-app#41]
For example
![image](https://user-images.githubusercontent.com/49697006/118427558-860b3680-b69b-11eb-8a31-bea4963bae6b.png)

**Comment by pierrelafitte** [comment]
Added custom icons to the aside menu and tab bar

<img width="1440" alt="Menu Items" src="https://user-images.githubusercontent.com/49452570/120246406-ad4b3180-c25f-11eb-898a-07c75c85c129.png">

**Comment by pierrelafitte** [comment]
Marked as complete and will be included in the next version.
