### ISSUE TITLE
Bottom menu overlapping page items

### ISSUE THREAD

**Issue by g45t345rt** [haven-protocol-org/haven-web-app#43]
Width of 576px to 991px

![image](https://user-images.githubusercontent.com/49697006/119239057-6a2ce800-bb14-11eb-8e46-e057d91aa1df.png)

Should be like that
![image](https://user-images.githubusercontent.com/49697006/119239114-efb09800-bb14-11eb-86b6-3cb978a6aaca.png)

**Comment by pierrelafitte** [comment]
I believe this auto fixes itself after you scroll. Somewhere i've probably messed up some kinda of css overflow element. 

<img width="452" alt="Mobile Height" src="https://user-images.githubusercontent.com/49452570/120246536-031fd980-c260-11eb-936e-4de79294c0aa.png">

**Comment by pierrelafitte** [comment]
Closing for now..
